### ISSUE TITLE
[BUG] Issue with Auto-loot Heavies v3a

### ISSUE THREAD

**Issue by yoyovero** [p1xel8ted/GraveyardKeeper#10]
**What mod/tool are you reporting a bug for?**
- Mod/tool : Auto-loot Heavies...Sort of
- Version : v3a

**Describe the bug**
- The mod seems not to be working, the config.ini file is empty.
![image](https://user-images.githubusercontent.com/47720051/173114597-bf26f29f-0f8d-4bfc-935b-73c2c819e66d.png)
I'm also using FogBeGone, UltraWide and SaveNow, these are working perfectly, config.ini, if exist, is written.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Install the mod via QMod Manager Reloaded
2. Launch the game

**Expected behavior**
- Heavies to teleport when picked/dropped, or text to be said by the character on the press of 5 to 9 keys, or config.ini to contain anything. The problem here is that nothing seems to actually happen at all.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/47720051/173115500-8a77fed2-f929-4c71-92ff-12fee005b7cc.png)
![image](https://user-images.githubusercontent.com/47720051/173115558-d955708a-3275-4ca2-92df-7fa495e737e1.png)
![image](https://user-images.githubusercontent.com/47720051/173115596-11a3213f-68c7-44f7-8e66-6de72d506a8d.png)

**Desktop (please complete the following information):**
- Windows version : W11, 21H2
- Windows language : French
- Game language : French/English
- Game platform : Steam

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
Interesting, all my mods use the same code for INI handling. Can you please confirm:
Before doing the below, please navigate to:

C:\Users\***\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper

and delete Player.log. Perform the actions below, and then attach the newly generated Player.log to your reply.

1. If you delete the file, and start the game with the mod enabled (and don't do anything), does it have contents.
2. If you press any of the config options (5-9) and alt-tab, and open the config file, does it have contents.
3. If you manually type in anything into the file, and start the game with the mod enabled, what happens to the file.

**Comment by Kiorn** [comment]
> 

Same issue.
1. Config.ini is empty.
2. Nothing changed. Config.ini is empty.
3. Typed "Still empty((", start the game, nothing changed, but appeared new file - Player-prev.log
[Player.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8884184/Player.log)
[Player-prev.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8884185/Player-prev.log)
![1](https://user-images.githubusercontent.com/107275974/173193664-af4b1e3e-ad88-42cb-b2a0-3abc0872a156.png)
![3](https://user-images.githubusercontent.com/107275974/173193685-600e26b9-72c0-479e-b26b-2772147468fa.png)
.

**Comment by p1xel8ted** [comment]
> > 
> 
> Same issue.
> 
> 1. Config.ini is empty.
> 2. Nothing changed. Config.ini is empty.
> 3. Typed "Still empty((", start the game, nothing changed, but there is a new file - Player-prev.log
>    [Player.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8884184/Player.log)
>    [Player-prev.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8884185/Player-prev.log)
>    ![1](https://user-images.githubusercontent.com/107275974/173193664-af4b1e3e-ad88-42cb-b2a0-3abc0872a156.png)
>    ![3](https://user-images.githubusercontent.com/107275974/173193685-600e26b9-72c0-479e-b26b-2772147468fa.png)
>    .

So even after running the game with the mod enabled and pressing the buttons, the config remained with the text "Still empty"?

In the game directory, there is a "qmod_reloaded_log.txt" - can you please either post it, or check for "Failed to patch" messages.

**Comment by Kiorn** [comment]
> So even after running the game with the mod enabled and pressing the buttons, the config remained with the text "Still empty"?

Yep, remained with the text "Still empty"

> In the game directory, there is a "qmod_reloaded_log.txt"

[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8885061/qmod_reloaded_log.txt)

![3234](https://user-images.githubusercontent.com/107275974/173211525-3c5292ab-dd5f-463a-9679-b96d6df9cd70.png)

> The config.ini you're editing, where is it located

.......\Graveyard Keeper\QMods\AutoLootHeavies

**Comment by p1xel8ted** [comment]
> > So even after running the game with the mod enabled and pressing the buttons, the config remained with the text "Still empty"?
> 
> Yep, remained with the text "Still empty"
> 
> > In the game directory, there is a "qmod_reloaded_log.txt"
> 
> [qmod_reloaded_log.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8885061/qmod_reloaded_log.txt)
>
> > The config.ini you're editing, where is it located
> 
> .......\Graveyard Keeper\QMods\AutoLootHeavies

All those "Invoking failed" messages mean the mods arent loading at all for some reason. Failed to patch the target basically. I'll have to compile a version with more logging enabled so I can see the error message as to why. I suspect something to do with the language (as they work fine on Eng/Eng), but no idea why.

**Comment by p1xel8ted** [comment]
Please delete all Player.log files and the qmod_reloaded_log.txt, replace the mod with both these files, and launch the game. Re-attach both logs after running the game. (this isn't a fix, just better error reporting so I can see where it's going wrong.)

[AutoLootHeavies-Test.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885119/AutoLootHeavies-Test.zip)

You will also need to replace the UnityPlayer.dll (next to the game EXE) with the one attached. Back it up first. This will put the game into Debug mode and allow me to see exactly what line the error is happening. The game is sluggish with debug mode, so don't leave it on.

[UnityPlayer.dll.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885120/UnityPlayer.dll.zip)

**Comment by Kiorn** [comment]
> Please delete all Player.log files and the qmod_reloaded_log.txt, replace the mod with both these files, and launch the game. Re-attach both logs after running the game. (this isn't a fix, just better error reporting so I can see where it's going wrong.)
> 
> [AutoLootHeavies-Test.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885119/AutoLootHeavies-Test.zip)
> 
> You will also need to replace the UnityPlayer.dll (next to the game EXE) with the one attached. Back it up first. This will put the game into Debug mode and allow me to see exactly what line the error is happening. The game is sluggish with debug mode, so don't leave it on.
> 
> [UnityPlayer.dll.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885120/UnityPlayer.dll.zip)

Done
[Player.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8885131/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8885132/qmod_reloaded_log.txt)

**Comment by p1xel8ted** [comment]
Give these a whirl. It was tripping on trying to read numbers that use . as the decimal separator.
Same as before.

[SaveNow-Maybe.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885151/SaveNow-Maybe.zip)
[AutoLootHeavies-Maybe.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8885152/AutoLootHeavies-Maybe.zip)

**Comment by Kiorn** [comment]
Works fine!
[Player.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8885180/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8885181/qmod_reloaded_log.txt)

**Comment by p1xel8ted** [comment]
> Works fine! [Player.log](https://github.com/p1xel8ted/GraveyardKeeper/files/8885180/Player.log) [qmod_reloaded_log.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8885181/qmod_reloaded_log.txt)

Nice! and config is being written ok?

**Comment by Kiorn** [comment]
> config is being written ok?

Forgot to add..
![5](https://user-images.githubusercontent.com/107275974/173214510-301322b6-0f6f-4f87-8649-20e5d7214db4.png)

**You are the best! Thanks!!!**

**Comment by p1xel8ted** [comment]
Beautiful, looks good. Appreciate the help! I'll close this, for now, thanks for raising it.
