### ISSUE TITLE
Issue with Queue Everything 

### ISSUE THREAD

**Issue by honorelle** [p1xel8ted/GraveyardKeeper#11]
Started a new game, took Gerry and body to graveyard with first corpse and can't place grave sites because there's now a quality craft box calling for softcover/hardcover books death certificates as the only option.

**Comment by honorelle** [comment]
[interacted-objects.txt](https://github.com/p1xel8ted/GraveyardKeeper/files/8883672/interacted-objects.txt)

**Comment by p1xel8ted** [comment]
What version etc? The template is there for a reason.

**Comment by p1xel8ted** [comment]
https://www.nexusmods.com/graveyardkeeper/mods/57?tab=files

1.1 was uploaded about 3 hours ago, fixes grave interactions. If the issue is different, please fill out the template.

**Comment by honorelle** [comment]
This is the new version, just downloaded. I wasn't using this mod before. Sorry managed to overlook the template, because I came straight to the issues tab.

Using Steam current version, only Stranger Sins DLC.
Bug. Interaction with Graveyard blueprint table and the Crematorium table have the same issue - no ability to craft anything, burial sites, flowerbeds, trunks etc are removed from relevant window,- I managed to screenshot it this time
(https://user-images.githubusercontent.com/107304067/173185340-49696046-7bc4-4c1f-a9c8-9912ce9c62a3.png)

There arent any steps beyond Step 1. Go to Graveyard bluprint table or Crematory blueprint table and Step 2 See Error.

**Comment by p1xel8ted** [comment]
No worries, interesting thought I already have checks in place against those specific objects.

What other mods, and what's your load order. A screenshot is fine.

**Comment by p1xel8ted** [comment]
> What mod/tool are you reporting a bug for?
> 
> ```
> Mod/tool Queue Everything
> Version  1.1
> ```
> 
> Describe the bug . Interaction with Graveyard blueprint table and the Crematorium table have the same issue - no ability to craft anything, burial sites, flowerbeds, trunks etc are removed from relevant window
> 
> To Reproduce Detailed steps to reproduce the behavior: There arent any steps beyond Step 1. Go to Graveyard bluprint table or Crematory blueprint table and Step 2 See Error.
> 
> Expected behavior
> 
> ```
> the normal function of those tables
> ```
> 
> Screenshots/Video
> 
> (https://user-images.githubusercontent.com/107304067/173185340-49696046-7bc4-4c1f-a9c8-9912ce9c62a3.png)
> 
> Desktop (please complete the following information):
> 
> ```
> Windows version 10
> Windows language English
> Game language English
> Game platform  Steam current version, only Stranger Sins DLC.
> ```
> 
> This is the new version, just downloaded. I wasn't using this mod before. Sorry managed to overlook the template, because I came straight to the issues tab.

No worries, interesting though, I already have checks in place against those specific objects.

What other mods, and what's your load order. A screenshot is fine. (or multiple if you have lots)

**Comment by p1xel8ted** [comment]
I can't reproduce what you're seeing. Started a new game with only Stranger Sins enabled and visited all the trouble spots, and they all work fine.
