### ISSUE TITLE
[BUG] More storage fixed (harmony 1-to-2 ver.) - Materials in the player's inventory are NOT included

### ISSUE THREAD

**Issue by Marianna-Milorzab** [p1xel8ted/GraveyardKeeper#16]
All installed mods:
![image](https://user-images.githubusercontent.com/78551038/173249299-f907c086-b8af-4760-a2ec-3dd1c990265b.png)

More storage fixed settings:
![image](https://user-images.githubusercontent.com/78551038/173249776-6f9787e8-c3bc-4492-a20c-79f3d8af162c.png)

**What mod/tool are you reporting a bug for?**
- More storage fixed
- Version: harmony 1-to-2

**Issue**
- When you have materials in your inventory, the crafting spots don't see them, they only see materials stored in the trunks, chests etc. So, for instance, if you have no materials in the trunks, only in the player's inventory, you are unable to craft items with them.

**Expected behavior**
- Materials in player's inventory should be seen by crafting spots and be usable by them.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/78551038/173249491-3ab478c6-c14a-49a2-9adc-b11d1798505b.png)

![image](https://user-images.githubusercontent.com/78551038/173249506-47ed8746-a428-4dbe-a186-7068ac2061d8.png)

The anvil should see 9 ingots instead of 7

**Desktop (please complete the following information):**
- Windows 10
- Windows language: ENglish
- Game language: English
- Game platform: gog

**Additional context**
- The issue doesn't occur in the OG harmony 1 version of the mod

**Comment by p1xel8ted** [comment]
This was the same behavior before I converted it. Also, there is no mod code change when converting old mods to Harmony2, just a different way to Patch. I use More Storage for more storage, but disable craft anywhere and use Shared Inventory as it works as intended. When I get more time, I'll take a look at fixing More Storage properly (unless the original author does it first)
