### ISSUE TITLE
How to start with GYK modding

### ISSUE THREAD

**Issue by saquili** [p1xel8ted/GraveyardKeeper#2]
Hello,
I am interested in creating mod to solve quality item crafting issue. You are probably familiar with this that you cannot craft multiple items that has quality. I tried to setup environment based on your source code but I am a bit new to modding games like that. I got a bit lost in how am I supposed to mod unity games, any help or tips would be appreciated.  Thank you in advance for any help you could provide.

**Comment by alca259** [comment]
Hello, for my experience, you must try at least a hello world mod. https://github.com/oldark87/GraveyardKeeper
For everything else, you should check out other mods and learn from them.

**Comment by p1xel8ted** [comment]
> Hello, I am interested in creating mod to solve quality item crafting issue. You are probably familiar with this that you cannot craft multiple items that has quality. I tried to setup environment based on your source code but I am a bit new to modding games like that. I got a bit lost in how am I supposed to mod unity games, any help or tips would be appreciated. Thank you in advance for any help you could provide.

That particular problem you've chosen to tackle is up there on the difficulty scale, especially if you don't have any experience. But similar to what @alca259 has said, start small. Also, read up on the Harmony basics as that's the modding framework we use.

https://harmony.pardeike.net/articles/intro.html

I have attached the project template I use for creating mods. Don't unzip it, just place it in:
[QMod Template.zip](https://github.com/p1xel8ted/GraveyardKeeper/files/8794567/QMod.Template.zip)

Documents\Visual Studio 2022\Templates\ProjectTemplates

Search Qmod when creating a new project.

You will need to change line 10 of MainPatcher.cs, "p1xel8ted.graveyardkeeper" to whatever you want.

`var val = HarmonyInstance.Create($"p1xel8ted.graveyardkeeper.$safeprojectname$");`

All the dependencies can be found within the game folder
...\Graveyard Keeper\Graveyard Keeper_Data\Managed

**The tools I use are:**

**Visual Studio 2022** (everything targeted to .NET 4.8) (with Unity for Visual Studio installed)

**dnSpy** - https://github.com/dnSpy/dnSpy/releases/tag/v6.1.8 - This is used to look at the game code, the great thing about dnSpy is you can edit the code, and recompile to see what happens prior to making a mod for it.

**JetBrains dotPeek** - This integrates into Visual Studio allowing you to Ctrl+Click game methods in your code and decompiles within Visual Studio.

**Unity 2020.3.17f1** - https://unity3d.com/get-unity/download/archive - The game uses this version, so it needs to match. You can convert the game into Development mode by copying:

`C:\Program Files\Unity\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win32_development_mono\UnityPlayer.dll`

into the root folder of Graveyard Keeper overwriting the original. Back it up first. Once that's done, you can launch the game, then attach Visual Studio to the game and debug your code while the game is running. It also shows a log on screen that you can write to by using Debug.LogError

**(Taken from Harmony discord)
Project setup for Unity 2017.2+ :**
- In Visual Studio, open your mod project
- In the "Project" menu, go to "myProject Properties"
- In the project properties window, make sure you're under the "Debug" configuration, then go to the "Build" tab
- Click on the "Advanced" button
- In the popup window, there is a "Debugging information" dropdown : select the "Portable" option
- Alternatively, you can edit your *.csproj file and under the "Debug" PropertyGroup, set <DebugType>portable</DebugType>
- When building your mod assembly in the "Debug" configuration, VS will generate a *.pdb file alongside your *.dll file. You need to copy that file alongside the dll to whatever location you're using for loading your mod into the game.

And finally, just look at everyone's mods using dnSpy/dotPeek (I prefer dnSpy) to see how they did what they did. The trick is finding where in the game to hook into.

Also, this is a GYK Modding Discord - https://discord.gg/s9jdMvSC
