### ISSUE TITLE
[BUG] Issue with mod/tool

### ISSUE THREAD

**Issue by skelhammer** [p1xel8ted/GraveyardKeeper#5]
**If the bug report is about QMod Manager Reloaded, a screenshot of the "Checklist" page must be attached. Any without will be ignored.**

**What mod/tool are you reporting a bug for?**
- QMod Manager Reloaded w/ any mods
- 1.0.8191.37079

**Describe the bug**
- No mods will load. All mods show "-1" in the "order" column, and I assume these 2 things are related 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Fresh install the Game and QMod Reloaded
2. Install any mod
3. No mods load, they all show -1 as the order

**Expected behavior**
- I expect mods to show a mod order and for them to load

**Screenshots/Video**
- ![image](https://user-images.githubusercontent.com/31297476/172293949-2074d1e4-841b-48a0-a181-da15e91c7cc1.png)

**Desktop (please complete the following information):**
- Windows Version - Windows 11
- Windows language - English
- Game language - English
- Game platform - Steam

**Comment by p1xel8ted** [comment]
It will still load at -1. If it's not loading (it will say "failed to invoke patch etc etc in the log), it means you downloaded the mod from question from Nexus, and not the updated version from this repository. All my mods, and the mod launcher use Harmony 2, whereas the old mods on Nexus require Harmony 1 - they are not cross compatible. I have updated the mods I can and placed them in this repository. Please note, this doesn't mean the mod will work, I didn't fix them in that regards, just updated what's need to get them to run. This information is on all the Descriptions of my mods. 

I personally use Not Keepers Speed, and can confirm it works.

Drag and drop the row and it will update to 1.

https://github.com/p1xel8ted/GraveyardKeeper/tree/main/Harmony1-to-2-Mods/DOWNLOAD%20THESE
